import React from "react";

const TermsConditions = () => {
  return (
    <div className="text-gray-800">
      {/* Banner Section */}
      <div className="bg-blue-100 py-8 px-4 mt-15 md:mt-15 md:px-10 text-center shadow-md">
        <h2 className="text-3xl md:text-4xl font-bold text-blue-700">
          Capital Curv
        </h2>
        <p className="mt-2 text-blue-600 text-base md:text-lg">
          Please take a moment to review our Terms & Conditions before using our
          platform.
        </p>
      </div>

      {/* Main Content */}
      <div className="px-6 py-10 max-w-4xl mx-auto">
        <h1 className="text-3xl md:text-4xl font-bold mb-6 text-center text-blue-700">
          Terms & Conditions
        </h1>
        <div className="space-y-6 text-justify">
          <p>
            1. This document is an electronic record in terms of Information
            Technology Act, 2000 and rules there under as applicable and the
            amended provisions pertaining to electronic records in various
            statutes as amended by the Information Technology Act, 2000. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures.
          </p>
          <p>
            2. This document is published in accordance with the provisions of
            Rule 3 (1) of the Information Technology (Intermediaries guidelines)
            Rules, 2011 that require publishing the rules and regulations,
            privacy policy and Terms of Use for access or usage of domain name
            https://capitalcurv.com ('Website'), including the related mobile
            site and mobile application (hereinafter referred to as 'Platform').
          </p>
          <p>
            3. The Platform is owned by AVINADO FINTECH SOLUTION PRIVATE
            LIMITED, a company incorporated under the Companies Act, 1956 with
            its registered office at 28-A, EAST LAXMI MARKET, East Delhi, Delhi,
            India ,New Delhi ,India (hereinafter referred to as ‘Platform
            Owner’, 'we', 'us', 'our').
          </p>
          <p>
            4. Your use of the Platform and services and tools are governed by
            the following terms and conditions (“Terms of Use”) as applicable to
            the Platform including the applicable policies which are
            incorporated herein by way of reference. If You transact on the
            Platform, You shall be subject to the policies that are applicable
            to the Platform for such transaction. By mere use of the Platform,
            You shall be contracting with the Platform Owner and these terms and
            conditions including the policies constitute Your binding
            obligations, with Platform Owner. These Terms of Use relate to your
            use of our website, goods (as applicable) or services (as
            applicable) (collectively, 'Services'). Any terms and conditions
            proposed by You which are in addition to or which conflict with
            these Terms of Use are expressly rejected by the Platform Owner and
            shall be of no force or effect. These Terms of Use can be modified
            at any time without assigning any reason. It is your responsibility
            to periodically review these Terms of Use to stay informed of
            updates.
          </p>
          <p>
            5. For the purpose of these Terms of Use, wherever the context so
            requires ‘you’, 'your' or ‘user’ shall mean any natural or legal
            person who has agreed to become a user/buyer on the Platform.
          </p>
          <p className="font-semibold uppercase">
            Accessing, browsing or otherwise using the platform indicates your
            agreement to all the terms and conditions under these terms of use,
            so please read the terms of use carefully before proceeding.
          </p>
          <section>
            <h2 className="text-xl font-semibold">User Guidelines</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                You agree to provide true, accurate and complete information to
                us during and after registration, and you shall be responsible
                for all acts done through the use of your registered account on
                the Platform.
              </li>
              <li>
                We do not guarantee the accuracy or completeness of the
                information provided via the Services, and shall not be held
                liable for any inaccuracies.
              </li>
              <li>
                Your use of our Services is solely at your own risk and
                discretion. Ensure the Services meet your needs before use.
              </li>
              <li>
                All content on the Platform is our proprietary property.
                Unauthorized use of our intellectual property is prohibited.
              </li>
              <li>
                Unauthorized use of the Platform or Services may lead to action
                under applicable laws.
              </li>
              <li>
                You agree to pay all charges associated with using the Services.
              </li>
              <li>
                You agree not to use the Platform or Services for any unlawful
                purposes.
              </li>
              <li>
                Third-party links provided are for information only; we are not
                responsible for their content or policies.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold">Transactions</h2>
            <p>
              You understand that by initiating a transaction for availing our
              Services, you are entering into a legally binding contract with
              the Platform Owner.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">Indemnity</h2>
            <p>
              You agree to indemnify and hold harmless the Platform Owner and
              its affiliates from any claims arising out of your breach of these
              Terms, violation of laws, or infringement of rights of others.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">Force Majeure</h2>
            <p>
              The Platform Owner is not liable for failure to perform due to
              circumstances beyond its control including natural disasters,
              internet outages, or government actions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">
              Governing Law and Jurisdiction
            </h2>
            <p>
              These Terms shall be governed by the laws of India. All disputes
              will be subject to the exclusive jurisdiction of courts in New
              Delhi and Delhi.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">Contact</h2>
            <p>
              Any concerns regarding these Terms must be addressed through the
              contact information available on our website.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">Eligibility</h2>
            <p>
              You must be at least 18 years old to register or use our Services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">Trading Nature</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                Capital Curv is not SEBI-registered and does not offer financial
                advice or brokerage services.
              </li>
              <li>
                All trading on the platform during evaluations is simulated and
                for educational purposes.
              </li>
              <li>
                Traders who pass evaluations trade real markets under a
                proprietary trading model via Angel One Order API.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold">Membership and Fees</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>Membership is required to participate in evaluations.</li>
              <li>
                Fees are non-refundable except in specific cases outlined in our
                Refund Policy.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold">Platform Conduct</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                Use only lawful methods and avoid unfair trading strategies like
                copy trading or account sharing.
              </li>
              <li>
                Do not misuse platform features or attempt unauthorized access.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold">Intellectual Property</h2>
            <p>
              All intellectual property on the Platform is the sole property of
              Capital Curv. Unauthorized use is prohibited.
            </p>
          </section>

          <p className="text-sm italic text-gray-500 text-center pt-6">
            By accessing, browsing, or using the Platform, you agree to be bound
            by these Terms and Conditions.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsConditions;
